<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Messages [<!ELEMENT Messages (Package*)>

<!ELEMENT Package (Error*)>
<!ATTLIST Package ID CDATA #REQUIRED>
<!ATTLIST Package DefaultComponent CDATA #REQUIRED>

<!ELEMENT Error (#PCDATA)>
<!ATTLIST Error Key CDATA #REQUIRED>
<!ATTLIST Error _locID CDATA "0">
<!ATTLIST Error Component CDATA #IMPLIED>
<!ATTLIST Error NativeErrorCode CDATA #REQUIRED>
<!ATTLIST Error Params CDATA "0">]>
<Messages>
    <!-- #################################################################################### -->
    <Package ID="1" DefaultComponent="ODBC">

      <!-- Errors and warnings in general operation. --> 
      <!-- Error thrown when an unexpected exception is caught. --> 
      <Error Key="GenErr" NativeErrorCode="10000" _locID="1.GenErr">Opšta greška: uhvaćen je neočekivani izuzetak.</Error>

      <!-- Same as GenErr, but allows for a custom message (say, from an std::exception) --> 
      <Error Key="GenErr1" Params="1" NativeErrorCode="10001" _locID="1.GenErr1">Opšta greška: %1%</Error>

      <!-- Error thrown when a std::bad_alloc exception is caught. --> 
      <Error Key="MemAllocErr" NativeErrorCode="10010" _locID="1.MemAllocErr">Greška u dodeli memorije: uhvaćen je izuzetak std::bad_alloc.</Error>

      <!-- Error thrown when ODBC functions are executed out of the allowed sequence as specified in the ODBC specification. --> 
      <Error Key="FuncSeqErr" NativeErrorCode="10020" _locID="1.FuncSeqErr">ODBC funkcije su izvršene iz dozvoljene sekvence.</Error>

      <!-- Error thrown when statement is invalid or not found. --> 
      <Error Key="InvalidStmt" NativeErrorCode="10040" _locID="1.InvalidStmt">Izjava nije važeća ili nije pronađena.</Error>

      <!-- Error thrown when connection is invalid or not found. --> 
      <Error Key="InvalidConn" NativeErrorCode="10050" _locID="1.InvalidConn">Veza je nevažeća ili nije pronađena.</Error>

      <!-- Error thrown when descriptor is invalid or not found. --> 
      <Error Key="InvalidAppDesc" NativeErrorCode="10060" _locID="1.InvalidAppDesc">Opis aplikacije je nevažeći ili nije pronađen.</Error>

      <!-- Error thrown when explicit application descriptor is invalid or not found. --> 
      <Error Key="InvalidExplAppDesc" NativeErrorCode="10070" _locID="1.InvalidExplAppDesc">Opis eksplicitne aplikacije nije važeći ili nije pronađen.</Error>

      <!-- Error thrown when query manager is invalid or not found. --> 
      <Error Key="InvalidQueryMgr" NativeErrorCode="10080" _locID="1.InvalidQueryMgr">Menadžer upita nije važeći ili nije pronađen.</Error>

      <!-- Error thrown when execution results are invalid or not found. --> 
      <Error Key="InvalidExecResults" NativeErrorCode="10090" _locID="1.InvalidExecResults">Rezultati izvršavanja su nevažeći ili nisu pronađeni.</Error>

      <!-- Errors and warnings with diagnostics reporting. --> 
      <!-- Error thrown when an invalid diagnostic identifier is used. --> 
      <Error Key="InvalidDiagIdent" NativeErrorCode="10110" _locID="1.InvalidDiagIdent">Korišćen je nevažeći dijagnostički identifikator.</Error>

      <!-- Error thrown when requesting for a diagnostic field in binary format while no binary diagnostic fields exist. -->
      <Error Key="NoBinaryDiagFields" NativeErrorCode="10120" _locID="1.NoBinaryDiagFields">Ne postoje binarna dijagnostička polja. Nije moguće vratiti dijagnostičko polje u binarnom formatu.</Error>


      <!-- Errors and warnings with the provided buffer and buffer length. --> 
      <!-- Error thrown when an invalid string or buffer length is provided by the application. --> 
      <Error Key="InvalidStrOrBuffLen" NativeErrorCode="10130" _locID="1.InvalidStrOrBuffLen">Aplikacija je navela nevažeću dužinu niske ili bafera.</Error>

      <!-- Warning posted when an output string is right truncated to fit into the output buffer. --> 
      <Error Key="StrRightTruncWarn" NativeErrorCode="10160" _locID="1.StrRightTruncWarn">Desno skraćivanje podataka niske: podaci niske su preveliki za bafer izlaznih podataka i skraćeni su.</Error>

      <!-- Error thrown when string data is too big for the driver's data buffer. --> 
      <Error Key="StrRightTruncErr" NativeErrorCode="10170" _locID="1.StrRightTruncErr">Desno skraćivanje podataka niske na podacima iz izvora podataka: podaci niske su preveliki za bafer podataka upravljačkog programa.</Error>

      <!-- Error thrown when an invalid output buffer is provided. --> 
      <Error Key="InvalidOutputBuff" NativeErrorCode="10180" _locID="1.InvalidOutputBuff">Naveden je nevažeći izlazni bafer.</Error>

      <!-- Error thrown when there is an invalid string truncation. --> 
      <Error Key="InvalidStrTrunc" NativeErrorCode="10190" _locID="1.InvalidStrTrunc">Nevažeće skraćivanje niske.</Error>


      <!-- Error and warnings with Attributes. --> 
      <!-- Error thrown when the attribute type specified is not supported for the current operation. --> 
      <Error Key="AttrTypeNotSupported" NativeErrorCode="10200" _locID="1.AttrTypeNotSupported">Tip atributa nije podržan za trenutnu operaciju.</Error>

      <!-- Error thrown when the attribute identifier specified is invalid or not supported. --> 
      <Error Key="InvalidAttrIdent" Params="1" NativeErrorCode="10210" _locID="1.InvalidAttrIdent">Identifikator atributa je nevažeći ili nije podržan: %1%</Error>

      <!-- Error thrown when setting the value of a read-only attribute. --> 
      <Error Key="CannotSetReadOnlyAttr" NativeErrorCode="10220" _locID="1.CannotSetReadOnlyAttr">Nije moguće podesiti atribut samo za čitanje.</Error>

      <!-- Error thrown when failed to retrieve an attribute value. --> 
      <Error Key="AttrValNotFound" NativeErrorCode="10230" _locID="1.AttrValNotFound">Nije moguće pribaviti vrednost atributa.</Error>

      <!-- Error thrown when setting the implementation descriptor handle, a statement's implementation descriptor cannot be replaced. --> 
      <Error Key="CannotSetImpDescHandle" NativeErrorCode="10240" _locID="1.CannotSetImpDescHandle">Nije moguće promeniti regulator opisa primene izjave.</Error>

      <!-- Error thrown when setting the value of SQL_ATTR_ASYNC_ENABLE statement attribute when driver does not support this operation. --> 
      <Error Key="SetAsyncEnabNotSupported" NativeErrorCode="10250" _locID="1.SetAsyncEnabNotSupported">Podešavanje atributa SQL_ATTR_ASYNC_ENABLE nije podržano.</Error>

      <!-- Error thrown when failed to obtain a connection attribute that is required to check if the current operation is valid. --> 
      <Error Key="ObtainCheckingConnAttrFailed" NativeErrorCode="10260" _locID="1.ObtainCheckingConnAttrFailed">Nije moguće pribaviti atribut veze potreban da bi se proverilo da li je trenutna operacija važeća.</Error>

      <!-- Error thrown when changing the option to enable auto population of IPD while driver does not support IPD auto population. --> 
      <Error Key="AutoPopIpdNotSupported" NativeErrorCode="10270" _locID="1.AutoPopIpdNotSupported">Automatsko popunjavanje IPD-a (opis parametra primene) nije podržano.</Error>

      <!-- Error thrown when setting an attribute to a value that is invalid. --> 
      <Error Key="InvalidAttrVal" NativeErrorCode="10280" _locID="1.InvalidAttrVal">Nevažeća vrednost atributa.</Error>

      <!-- Warning posted when setting an attribute value that is not supported or invalid, and the driver was able to substitute a similar value. --> 
      <Error Key="OptAttrValChangedWarn" NativeErrorCode="10290" _locID="1.OptAttrValChangedWarn">Vrednost atributa nije podržana ili nije važeća, tako da je slična vrednost atributa zamenjena. Preuzmite vrednost atributa da biste videli zamenu.</Error>

      <!-- Error thrown when failing to revert a temporarily substituted attribute value back to its original value. --> 
      <Error Key="RevertAttrValueToOrigFailed" NativeErrorCode="10300" _locID="1.RevertAttrValueToOrigFailed">Nije moguće vratiti privremenu vrednost atributa na prvobitnu vrednost.</Error>

      <!-- Error thrown when failing to obtain a default value for a statement attribute during statement creation. --> 
      <Error Key="ObtainDefaultStmtAttrValueFailed" NativeErrorCode="10310" _locID="1.ObtainDefaultStmtAttrValueFailed">Nije moguće pribaviti podrazumevanu vrednost atributa izjave.</Error>

      <!-- Error thrown when setting an explicit application descriptor handle on a statement that is not from the statement's parent connection. --> 
      <Error Key="ExplAppDescHandleNotFromSameConn" NativeErrorCode="10320" _locID="1.ExplAppDescHandleNotFromSameConn">Regulator opisa eksplicitne aplikacije nije iz iste veze kao ciljna izjava.</Error>

      <!-- Error thrown when setting an implicit application descriptor handle on a statement but the descriptor was not one of the target statement's original implicit application descriptors. --> 
      <Error Key="ImplicitAppDescHandleNotOrig" NativeErrorCode="10330" _locID="1.ImplicitAppDescHandleNotOrig">Regulator opisa implicitne aplikacije nije prvobitni opis implicitne aplikacije ciljne izjave.</Error>

      <!-- Error and warnings with establishing connection to data source. -->
      <!-- Error thrown when the connection string is not of valid form. -->
      <Error Key="InvalidConnStr" NativeErrorCode="10360" _locID="1.InvalidConnStr">Nevažeća niska veze.</Error>

      <!-- Error thrown when the connection string does not contain information requested by the driver. -->
      <Error Key="InvalidConnStrAttr" NativeErrorCode="10370" _locID="1.InvalidConnStrAttr">Nevažeći atribut niske veze koji se ne podudara sa informacijama koje zahteva upravljački program.</Error>

      <!-- Error thrown when unable to establish a connection with the data source. -->
      <Error Key="UnableToEstConn" Params="1" NativeErrorCode="10380" _locID="1.UnableToEstConn">Nije moguće uspostaviti vezu sa izvorom podataka. Nedostaju podešavanja: %1%</Error>

      <!-- Error thrown when failed to obtain connection information through the driver provided dialog box. -->
      <Error Key="UpdateConnSettingsWithDiaglogFailed" NativeErrorCode="10390" _locID="1.UpdateConnSettingsWithDiaglogFailed">Ažuriranje podešavanja veze upitom dijaloga nije uspelo.</Error>

      <!-- Error thrown when performing an operation that requires an established connection but no connection has been established yet. -->
      <Error Key="NoEstConn" NativeErrorCode="10400" _locID="1.NoEstConn">Trenutna operacija zahteva uspostavljenu vezu, ali veza još uvek nije uspostavljena.</Error>

      <!-- Error thrown when trying to establish a connection but a connection already exist. -->
      <Error Key="ConnAlreadyEst" NativeErrorCode="10410" _locID="1.ConnAlreadyEst">Veza je već uspostavljena.</Error>

      <!-- Error thrown when data source did not provide a valid response. -->
      <Error Key="DataSourceDidNotGiveProperResp" NativeErrorCode="10420" _locID="1.DataSourceDidNotGiveProperResp">Izvor podataka nije naveo odgovarajući odgovor.</Error>

      <!-- Error thrown when application did not provide enough information to establish a connection to the data source but application specified that driver should not prompt application for more information. -->
      <Error Key="NotEnoughConnInfoButDriverNoPrompt" Params="1" NativeErrorCode="10430" _locID="1.NotEnoughConnInfoButDriverNoPrompt">Nije obezbeđeno dovoljno informacija za uspostavljanje veze sa izvorom podataka, a navedeno je da ne treba tražiti dodatne informacije. Nedostaju potrebna podešavanja: %1%</Error>

      <!-- Error thrown when driver complete flag is invalid or not supported. -->
      <Error Key="InvalidDriverComplFlag" NativeErrorCode="10440" _locID="1.InvalidDriverComplFlag">Zastavica za završetak rada upravljačkog programa nije važeća ili nije podržana.</Error>

      <!-- Error thrown when driver needs an indicator buffer to indicate NULL output data to the application but the application did not provide such buffer. -->
      <Error Key="NullIndPtrNotSupplied" NativeErrorCode="10450" _locID="1.NullIndPtrNotSupplied">Upravljački program zahteva pokazivač indikatora da bi se ukazalo na NULL izlazne podatke, ali on nije naveden.</Error>

      <!-- Error thrown when data conversion could not complete properly. -->
      <Error Key="DataConvError" NativeErrorCode="10460" _locID="1.DataConvError">Greška tokom konverzije podataka.</Error>

      <!-- Error thrown when data conversion is not supported. -->
      <Error Key="DataConvNotSupported" NativeErrorCode="10470" _locID="1.DataConvNotSupported">Konverzija podataka nije podržana.</Error>

      <!-- Error thrown when fetch orientation is not compatible with current settings. -->
      <Error Key="FetchTypeNotSupported" NativeErrorCode="10480" _locID="1.FetchTypeNotSupported">Tip dobavljanja nije podržan jer položaj dobavljanja nije kompatibilan sa trenutnim podešavanjima.</Error>

      <!-- Error thrown when cursor is in an invalid position for fetching data. -->
      <Error Key="InvalidCursorPos" NativeErrorCode="10490" _locID="1.InvalidCursorPos">Kursor je bio postavljen na položaj pre početka ili posle završetka skupa rezultata.</Error>

      <!-- Error thrown when cursor is forward-only and SetPos is called while on a valid row. -->
      <Error Key="InvalidForwardSetPosOper" NativeErrorCode="10495" _locID="1.InvalidForwardSetPosOper">SQLSetPos je nevažeća operacija kada se kursor kreće samo unapred.</Error>

      <!-- Error thrown when cursor is not of a supported type. -->
      <Error Key="InvalidCursorType" NativeErrorCode="10500" _locID="1.InvalidCursorType">Tip kursora nije važeći ili nije podržan.</Error>

      <!-- Error thrown when cursor is in an invalid state. -->
      <Error Key="InvalidCursorState" NativeErrorCode="10510" _locID="1.InvalidCursorState">Nevažeći status kursora.</Error>

      <!-- Error thrown when there is no more data left to fetch. -->
      <Error Key="NoMoreDataToFetch" NativeErrorCode="10530" _locID="1.NoMoreDataToFetch">Nema više podataka za dobavljanje.</Error>

      <!-- Error thrown when getting data that has already been fetched, but current settings do not allow this behavior. -->
      <Error Key="NotAllowedToGetSpecifiedColumn" NativeErrorCode="10540" _locID="1.NotAllowedToGetSpecifiedColumn">Nije dozvoljeno preuzimanje podataka koji su već dobavljeni za navedenu kolonu.</Error>

      <!-- Error thrown when requesting a column in the result set but no matching column is found. -->
      <Error Key="InvalidColNumInResultSet" NativeErrorCode="10550" _locID="1.InvalidColNumInResultSet">Nevažeći broj kolone skupa rezultata, nije pronađena podudarna kolona.</Error>

      <!-- Error thrown when checking the status of a fetched row but the status is invalid and not recognized. -->
      <Error Key="InvalidRowStatus" NativeErrorCode="10560" _locID="1.InvalidRowStatus">Nakon operacije dobavljanja otkriven je nevažeći status reda.</Error>

      <!-- Error thrown when changing types between multipart SQLGetData() calls. -->
      <Error Key="ChangeTypesInMultipartSQLGetDataNotSupported" NativeErrorCode="10570" _locID="1.ChangeTypesInMultipartSQLGetDataNotSupported">Promena tipova između višedelnih SQLGetData() poziva nije podržana.</Error>

      <!-- Error thrown when the source data is invalid (i.e. null when it shouldn't be. -->
      <Error Key="InvalidSrcData" NativeErrorCode="10580" _locID="1.InvalidSrcData">Izvorni podaci su nevažeći.</Error>

      <!-- Error thrown when there is no more data to get. -->
      <Error Key="NoMoreDataToGet" NativeErrorCode="10590" _locID="1.NoMoreDataToGet">Nema više podataka za preuzimanje.</Error>

      <!-- Error thrown when the conversion strategy is invalid (i.e. null when it shouldn't be). -->
      <Error Key="InvalidStrategy" NativeErrorCode="10600" _locID="1.InvalidStrategy">Strategija konverzije nije važeća.</Error>

      <!-- Error thrown when the conversion strategy is not supported. -->
      <Error Key="StrategyNotSupported" NativeErrorCode="10610" _locID="1.StrategyNotSupported">Strategija konverzije nije podržana.</Error>

      <!-- Error thrown when a conversion is attempted when there is more data. -->
      <Error Key="CannotConvWhileHasMoreData" NativeErrorCode="10620" _locID="1.CannotConvWhileHasMoreData">Nije moguće izvršiti konverziju kada postoji više podataka.</Error>

      <!-- Error thrown when the result of a conversion is invalid. -->
      <Error Key="InvalidConvResult" NativeErrorCode="10630" _locID="1.InvalidConvResult">Nevažeći rezultat konverzije.</Error>

      <!-- Error thrown when a flush fails to clear the data. -->
      <Error Key="FlushFailed" NativeErrorCode="10640" _locID="1.FlushFailed">Pražnjenje nije uspelo da obriše podatke.</Error>

      <!-- Error thrown when execution expects a result set but no result set is available from the DSII. -->
      <Error Key="NoAvailableResultSet" NativeErrorCode="10651" _locID="1.NoAvailableResultSet">Nijedan skup rezultata nije dostupan nakon izvršavanja, ali je jedan bio dostupan nakon pripreme.</Error>


      <!-- Error and warnings with descriptors. -->
      <!-- Error thrown when requesting a bookmark column but bookmark columns are not supported. -->
      <Error Key="BookmarkColumnNotSupported" NativeErrorCode="10660" _locID="1.BookmarkColumnNotSupported">Kolona obeleživača nije podržana.</Error>

      <!-- Error thrown when requesting a descriptor record or its information, but the descriptor record cannot be found -->
      <Error Key="InvalidDescIndex" NativeErrorCode="10670" _locID="1.InvalidDescIndex">Nevažeći indeks opisa, zapis opisa ne postoji ili nije pravilno pokrenut.</Error>

      <!-- Error thrown when requesting a descriptor field that is not supported or is invalid. -->
      <Error Key="InvalidDescFieldIdent" NativeErrorCode="10680" _locID="1.InvalidDescFieldIdent">Identifikator polja za opis nije važeći ili nije podržan.</Error>

      <!-- Error thrown when descriptor records are not sequential during query execution. -->
      <Error Key="DescRecNotSeq" NativeErrorCode="10690" _locID="1.DescRecNotSeq">Najmanje jedan očekivani zapis opisa ne postoji tokom izvršavanja upita.</Error>

      <!-- Error thrown when retrieving the SQL_DESC_COUNT field that is zero for a IRD. -->
      <Error Key="InvalidDescCount" NativeErrorCode="10700" _locID="1.InvalidDescCount">Nevažeće polje broja opisa, nema broja koji treba vratiti.</Error>

      <!-- Error thrown when setting a read-only descriptor field. -->
      <Error Key="ReadOnlyDescField" NativeErrorCode="10710" _locID="1.ReadOnlyDescField">Polje opisa samo za čitanje.</Error>

      <!-- Error thrown when registering or unregistering a listener (statement) on a non-explicit descriptor. -->
      <Error Key="CannotAssocNonExpDescWithDeleteListener" NativeErrorCode="10720" _locID="1.CannotAssocNonExpDescWithDeleteListener">Nije moguće povezati neeksplicitne opise sa osluškivačima opisa koji se koriste za čišćenje brisanja.</Error>

      <!-- Error thrown when getting the parent connection of a non-explicit descriptor. -->
      <Error Key="CannotGetParentConnOnNonExpDesc" NativeErrorCode="10730" _locID="1.CannotGetParentConnOnNonExpDesc">Nije moguće preuzeti nadređenu vezu na neeksplicitnom opisu.</Error>

      <!-- Error thrown when dropping descriptor record of an implementation row descriptor. -->
      <Error Key="CannotDropRecOfImplRowDesc" NativeErrorCode="10740" _locID="1.CannotDropRecOfImplRowDesc">Nije moguće otpustiti zapis opisa reda za primenu.</Error>

      <!-- Error thrown when an invalid or not supported datetime subcode identifier is given. -->
      <Error Key="InvalidDatetimeSubcodeIdent" NativeErrorCode="10750" _locID="1.InvalidDatetimeSubcodeIdent">Identifikator potkoda za Datetime nije važeći ili nije podržan.</Error>

      <!-- Error thrown when an invalid or not supported interval subcode identifier is given. -->
      <Error Key="InvalidIntevalSubcodeIdent" NativeErrorCode="10760" _locID="1.InvalidIntevalSubcodeIdent">Identifikator potkoda intervala nije važeći ili nije podržan.</Error>

      <!-- Error thrown when requesting a descriptor field that is not supported or invalid. -->
      <Error Key="DescFieldNotSupported" NativeErrorCode="10770" _locID="1.DescFieldNotSupported">Polje za opis nije važeće ili nije podržano.</Error>

      <!-- Error thrown when using a non-string method to get a string descriptor field. -->
      <Error Key="CannotGetStrDescFieldInNonStrMethod" NativeErrorCode="10780" _locID="1.CannotGetStrDescFieldInNonStrMethod">Nevažeća upotreba metoda koji nije niska da bi se dobilo polje opisa niske.</Error>

      <!-- Error thrown when specifying a descriptor field type that is not valid or not supported -->
      <Error Key="InvalidDescFieldType" NativeErrorCode="10790" _locID="1.InvalidDescFieldType">Tip polja za opis nije važeći ili nije podržan.</Error>

      <!-- Error thrown when the specified descriptor record cannot be found. -->
      <Error Key="DescRecNotFound" NativeErrorCode="10800" _locID="1.DescRecNotFound">Zapis opisa nije pronađen.</Error>

      <!-- Error thrown when setting SQL_DESC_UNNAMED to SQL_NAMED which is not allowed. -->
      <Error Key="DescUnnamedNotAllowed" NativeErrorCode="10810" _locID="1.DescUnnamedNotAllowed">Nije dozvoljeno postaviti SQL_DESC_UNNAMED na SQL_NAMED.</Error>

      <!-- Error thrown when performing an operation which requires the statement to be prepared but is not. -->
      <Error Key="StmtNotPrep" NativeErrorCode="10820" _locID="1.StmtNotPrep">Izjava nije pripremljena.</Error>

      <!-- Error thrown when setting or getting a descriptor field value that is not supported. -->
      <Error Key="DescFieldValueNotSupported" Params="2" NativeErrorCode="10830" _locID="1.DescFieldValueNotSupported">Polje za opis %1% ne podržava vrednost %2%.</Error>

      <!-- Error thrown when application modifies an implementation row descriptor -->
      <Error Key="CannotModImpRowDesc" NativeErrorCode="10840" _locID="1.CannotModImpRowDesc">Nije moguće izmeniti opise redova primene.</Error>

      <!-- Error thrown when setting the SQL_DESC_ALLOC_TYPE descriptor field. -->
      <Error Key="CannotSetDescAllocType" NativeErrorCode="10850" _locID="1.CannotSetDescAllocType">Nije moguće podesiti opis SQL_DESC_ALLOC_TYPE.</Error>

      <!-- Error thrown when an illegal descriptor type is detected. -->
      <Error Key="IllegalDescType" NativeErrorCode="10860" _locID="1.IllegalDescType">Otkriven je nedozvoljen tip opisa.</Error>

      <!-- Error thrown when an illegal descriptor concise type is detected -->
      <Error Key="IllegalDescConciseType" NativeErrorCode="10870" _locID="1.IllegalDescConciseType">Nedozvoljen koncizan tip opisa.</Error>

      <!-- Error thrown when an invalid or not supported datetime interval code is given. -->
      <Error Key="InvalidDatetimeCodeIdent" NativeErrorCode="10880" _locID="1.InvalidDatetimeCodeIdent">Kôd intervala za Datetime nije važeći ili nije podržan.</Error>

      <!-- Error thrown when an invalid or not supported interval code is given. -->
      <Error Key="InvalidIntervalCode" NativeErrorCode="10890" _locID="1.InvalidIntervalCode">Kôd intervala nije važeći ili nije podržan.</Error>


      <!-- Error and warnings with SQL statement execution. -->
      <!-- Error thrown when reading from an output parameter. -->
      <Error Key="CannotReadFromOutputParam" NativeErrorCode="10900" _locID="1.CannotReadFromOutputParam">Nije moguće čitati iz izlaznog parametra.</Error>

      <!-- Error thrown when reading from a default input parameter. -->
      <Error Key="CannotReadFromDefaultParam" NativeErrorCode="10910" _locID="1.CannotReadFromDefaultParam">Nije moguće dobiti nikakve podatke od podrazumevanog ulaznog parametra.</Error>

      <!-- Error thrown when reading from an input parameter which value has already been pushed down. -->
      <Error Key="CannotReadFromPushedParam" NativeErrorCode="10920" _locID="1.CannotReadFromPushedParam">Nije moguće dobiti nikakve podatke od ulaznog parametra čija je vrednost već pomerena nadole.</Error>

      <!-- Error thrown when writing to a default output parameter. -->
      <Error Key="WriteToDefaultParam" NativeErrorCode="10930" _locID="1.WriteToDefaultParam">Nije moguće upisivanje u podrazumevani parametar.</Error>

      <!-- Error thrown when writing to an input parameter -->
      <Error Key="WriteToInputParam" NativeErrorCode="10940" _locID="1.WriteToInputParam">Nije moguće upisivanje u ulazni parametar.</Error>

      <!-- Error thrown when received an execute result status code that is not recognizable. -->
      <Error Key="InvalidExecStatusCode" NativeErrorCode="10950" _locID="1.InvalidExecStatusCode">Kôd statusa rezultata izvršavanja nije važeći ili nije podržan.</Error>

      <!-- Error thrown when sending concatenated data that is not binary nor character. -->
      <Error Key="SendNonCharBinaryConcatData" NativeErrorCode="10970" _locID="1.SendNonCharBinaryConcatData">Nije moguće spojiti i poslati podatke koji nisu znakovni ili binarni.</Error>

      <!-- Error thrown when sending concatenated data that is a default or null parameter. -->
      <Error Key="SendConcatDataForDefaultOrNullParam" NativeErrorCode="10980" _locID="1.SendConcatDataForDefaultOrNullParam">Nije moguće spojiti i poslati podatke u delovima za podrazumevani parametar bez vrednosti.</Error>

      <!-- Error thrown when getting SQLGetInfo field which is not supported. -->
      <Error Key="InvalidGetInfoField" NativeErrorCode="10990" _locID="1.InvalidGetInfoField">Polje SQLGetInfo nije važeće ili nije podržano.</Error>

      <!-- Error thrown when getting query executor from catalog query manager.  Catalog functions are already executed thus has not query executor. -->
      <Error Key="NoQueryExecutor" NativeErrorCode="11000" _locID="1.NoQueryExecutor">Za menadžera upita kataloga ne postoji izvršilac upita.</Error>

      <!-- Error thrown when there is no data-at-execution parameter detected for query executor. -->
      <Error Key="NoDataAtExecParameter" NativeErrorCode="11010" _locID="1.NoDataAtExecParameter">Nema parametra za podatke pri izvršavanju.</Error>

      <!-- Error thrown when querying a parameter source during auto population. -->
      <Error Key="CannotQueryParmSrcDuringPopulate" NativeErrorCode="11020" _locID="1.CannotQueryParmSrcDuringPopulate">Tokom automatskog popunjavanja parametara nad informacijama nije moguće izvršiti upit o izvoru parametara.</Error>

      <!-- Error thrown when setting fields of a parameter source during parameter data pushing. -->
      <Error Key="CannotSetParmSrcAttrDuringPushData" NativeErrorCode="11030" _locID="1.CannotSetParmSrcAttrDuringPushData">Nije moguće podesiti atribute izvora parametra tokom prosleđivanja podataka o parametru.</Error>

      <!-- Error thrown when querying push value status while not performing execution.  -->
      <Error Key="PushValueStatusUnknown" NativeErrorCode="11040" _locID="1.PushValueStatusUnknown">Za status vrednosti prosleđivanja moguće je obaviti upit samo tokom izvršavanja.</Error>

      <!-- Error thrown when registering a parameter but not allowed in current state of execution. -->
      <Error Key="ParamRegistNotPermit" NativeErrorCode="11050" _locID="1.ParamRegistNotPermit">Registracija parametara nije dozvoljena.</Error>

      <!-- Error thrown when invalid parameter index used for parameter registration. -->
      <Error Key="InvalidParamRegistIndex" NativeErrorCode="11060" _locID="1.InvalidParamRegistIndex">Za registraciju se koristi nevažeći indeks parametra.</Error>

      <!-- Error thrown when descriptor field value is not recognizable. -->
      <Error Key="DescFieldNotRecg" NativeErrorCode="11070" _locID="1.DescFieldNotRecg">Vrednost polja za opis nije prepoznata.</Error>

      <!-- Error thrown when parameter type is invalid or not supported  -->
      <Error Key="InvalidParameterType" NativeErrorCode="11080" _locID="1.InvalidParameterType">Tip parametra nije važeći ili nije podržan.</Error>


      <!-- Error and warnings with connection and statement. -->
      <!-- Error thrown when setting a cursor name that is longer than the maximum limit. -->
      <Error Key="CursorNameTooLong" NativeErrorCode="11100" _locID="1.CursorNameTooLong">Naziv kursora je predugačak.</Error>

      <!-- Error thrown when setting a cursor name that is already in use. -->
      <Error Key="DuplicateCursorName" NativeErrorCode="11110" _locID="1.DuplicateCursorName">Duplirani naziv kursora.</Error>

      <!-- Error thrown when there are outstanding transactions when attempting to disconnect. -->
      <Error Key="OutstandingTransDuringDisconn" NativeErrorCode="11120" _locID="1.OutstandingTransDuringDisconn">Otvorene transakcije tokom prekida veze.</Error>

      <!-- Error thrown when using a connection to allocate a resource that is not statement nor descriptor. -->
      <Error Key="AllocNonStmtDescInConn" NativeErrorCode="11130" _locID="1.AllocNonStmtDescInConn">Nije moguće koristiti vezu za dodeljivanje resursa koji nije izjava i nije opis.</Error>

      <!-- Error thrown when using a connection to free a resource that is not statement nor descriptor. -->
      <Error Key="FreeNonStmtDescInConn" NativeErrorCode="11140" _locID="1.FreeNonStmtDescInConn">Nije moguće koristiti vezu za oslobađanje resursa koji nije izjava i nije opis.</Error>

      <!-- Error thrown when freeing an implicit application descriptor. -->
      <Error Key="FreeImplicitAppDesc" NativeErrorCode="11150" _locID="1.FreeImplicitAppDesc">Nije moguće osloboditi implicitni opis aplikacije.</Error>

      <!-- Error thrown when dropping an implicit application descriptor from its parent statement. -->